name: Flask App Deployment
on:
  workflow_dispatch:
    push:
      branches:
        - testbranch

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: install dependencies
        run: pip install ruff

      - name: Run linter
        run: ruff check .

  test:
    strategy:
      matrix:
        OS: ["ubuntu-24.04", "ubuntu-22.04", "macos-15", "macos-14", "macos-13", "windows-2025", "windows-2022", "windows-2019"]
        python-version: ["3.13", "3.12", "3.11", "3.10", "3.9"]  
    runs-on: ${{ matrix.OS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        continue-on-error: true
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Create cache directory for Linux and macOS
        if: runner.os != 'Windows'
        shell: bash
        run: mkdir -p "./.cache/pip"
        
      - name: Create cache directory for Windows
        if: runner.os == 'Windows'
        shell: cmd
        run: mkdir .\.cache\pip
      
      - name: Cache Python packages
        id: cache-python
        uses: actions/cache@v4
        with:
          path: ./.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        if: steps.cache-python.outputs.cache-hit != 'true'
        run: python -m pip install --cache-dir=./.cache/pip -r requirements.txt

      - name: Run Unit Test
        run: python -m pytest tests/ -v
