name: Flask App Deployment
on: workflow_dispatch

jobs:
  deploy-web_app:
    runs-on: ubuntu-24.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
    outputs:
      app_url: ${{ steps.get_app_url.outputs.app_url }}
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create zip file for Dockerrun.aws.json
        run: |
          chmod +x zip-Dockerrun.aws.json.sh
          ./zip-Dockerrun.aws.json.sh
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1
      
      - name: Terraform initialise
        run: terraform init

      - name: Terraform apply
        run: |
          terraform apply -auto-approve

      - name: Get app_url output from Terraform
        id: get_app_url
        run: echo "app_url=$(terraform output -raw app_url)" >> $GITHUB_OUTPUT
